### ISSUE TITLE
Decide what component library to use to cut down on development time.

### ISSUE THREAD

**Issue by Weffe** [CSUFTitanRover/TitanRover2018#1]
Options: 
1. blueprintjs (http://blueprintjs.com/)
2. semantic-ui react (https://react.semantic-ui.com)
3. material-ui [v1.0.0-beta.8] (https://material-ui-1dab0.firebaseapp.com/getting-started/usage/)
4. ant design (https://ant.design/docs/react/introduce)

What do you think is the best library from these 4? Do you have any other suggestions?

**Comment by Weffe** [comment]
### Blueprintjs

Pros:
- Thorough documentation on all components
- Written with typescript so type hinting comes free of charge with using any component
- Has a cool Hotkeys component already provided

Cons:
- No "Grid" or "Layout" component 
- (Not necessarily a con) Only built with Desktop enviroment in mind

### Semantic-UI

Pros:
- Good docs 
- Full list of components
- Includes "Grid" component
- Built with Responsiveness in mind

Cons:
- Some components can be basic and adding extra behavior will need to be done if needed

###  Material-UI (v1.0.0-beta.8)

Pros:
- Has "Grid" component for layout
- Nice docs with examples
- Good list of components

Cons:
- Seems like there might be a small learning curve with using the Higher Order Components the library provides

### Ant Design

Pros:
- Most components have built-in functionality 
- Nice design

Cons:
- Docs aren't very thorough
- It's maintianed by a Chinese community so most answers to issues are in Mandarin

**Comment by audstanley** [comment]
Do we even need bluejay?  Promises are now apart of NodeJs.

**Comment by audstanley** [comment]
...as for UI, I'll look into the ones you recommend.  My front end Js needs SERIOUS work.

**Comment by Weffe** [comment]
I was giving some serious thought this morning on this issue and I am heavily leaning towards Material-UI. It comes with a lot of good components and I believe it will fit the needs of the UI. 

> material-ui [v1.0.0-beta.8] (https://material-ui-1dab0.firebaseapp.com/getting-started/usage/)

As per promises, I think you confused [BLUEPRINT ](http://blueprintjs.com/) with [Bluebird ](https://github.com/petkaantonov/bluebird) and no we don't need bluebird if we are using any version of Node that supports promises.

**Comment by audstanley** [comment]
I'm checking out Material-UI right now.  I've got node version 8.5.0 running on the TX2.  I'm going to install [pm2](http://pm2.keymetrics.io/) also.  If we don't need it, then we don't need it, but it could be useful.

**Comment by Weffe** [comment]
It's been decided we will use Material-UI
(https://material-ui-1dab0.firebaseapp.com/getting-started/usage/)
