### ISSUE TITLE
Decide what color theme this year's UI will be.

### ISSUE THREAD

**Issue by Weffe** [CSUFTitanRover/TitanRover2018#2]
Light or Dark?

**Comment by Weffe** [comment]
Should the UI be like last years? Dark for the navbar and topbar and light for the main content? OR should it just be all dark this year?

**Comment by skrapmi** [comment]
I vote to make the UI school colors

**Comment by audstanley** [comment]
I vote Dark.

**Comment by Hawkinsonb** [comment]
School colors

**Comment by Weffe** [comment]
Took in all of your preferences so it's going to be like last year's and we'll try and sprinkle some school colors in 😃
